Dev solarthermal
BETALAB-team/EUReCA pull request #13
Opened 2024-08-30 14:38 UTC by Mohamad-k97

added class of solar thermal collector
added solar_gain_calculation into the systems.py

2024-09-02 07:35 UTC, enrico-prataviera requested changes

2024-09-02 07:35 UTC, enrico-prataviera commented on eureca_building/building.py
> +            solar_gain =0
Queste 5 righe servono? dovrebbero essere dentro la classe heating  system

2024-09-02 07:35 UTC, enrico-prataviera commented on eureca_building/building.py
> +            'Non-Renewable DHW [Wh]' : np.zeros([CONFIG.number_of_time_steps, 1]),
Non mettere queste variabili di output. Ne discutiamo

2024-09-02 07:35 UTC, enrico-prataviera commented on eureca_building/building.py
> +        self.add_solar_thermal(weather_object)
Questa funzone va messa a livello city, **non qui dentro**.

2024-09-02 07:35 UTC, enrico-prataviera commented on eureca_building/systems.py
> +            self.solar_thermal_gain=0
Eviterei di creare un altro attributo self.solar_thermal_gain quando c'è gia self.solar_gain

metterei così:

solar_gain = self.solar_gain[timestep]/CONFIG.ts_per_hour if isinstance("solar_gain", np.array) else 0

In questo modo vado a prendere il numpy se c'è st altrimento prende 0

Forse si possono togliere tutti i solar_gain = 0 in tutte le classi. Ne parliamo

2024-09-02 07:35 UTC, enrico-prataviera commented on eureca_building/thermal_storage_v01.py
> +class ThermalStorageTank_TES01:
Questa classe non viene usata al momento, giusto?

2024-09-02 08:28 UTC, Mohamad-k97 commented on eureca_building/building.py
> +            solar_gain =0
no, non servivano. avevo dimenticato di eliminarle

2024-09-02 08:38 UTC, Mohamad-k97 commented on eureca_building/thermal_storage_v01.py
> +class ThermalStorageTank_TES01:
sì, l'ho rimossa.

2024-09-02 12:03 UTC, Mohamad-k97 commented
rimosso le righe che non servivano di piu'
aggiunto add_solar_thermal dentro city. l'utente puo' aggiungere "ST" nella colonna di "Solar Technologies" per attivare il calcolo di solare termico. ("PV,ST"=con entrambe le technologie.)


--- ancora da fare: aggiungere un metodo per dimensionamento dei panelli di solare termico basato ai consumi ACS dell'edificio.

2024-09-05 06:49 UTC, enrico-prataviera commented
Serve fare altro? posso fare il merge?

2024-09-05 07:58 UTC, merged